# Publish all joint states -----------------------------------
joint_states_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Velocity Controllers ---------------------------------------
left_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: left_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

right_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: right_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}


