<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="oryksbot">

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/</robotNamespace>
        </plugin>
    </gazebo> 

    <!-- Joint state publisher plugin -->
    <gazebo>
        <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
            <robotNamespace>/</robotNamespace>
            <jointName>caster_joint</jointName>
            <updateRate>100</updateRate>
        </plugin> 
    </gazebo>        

    <gazebo>
        <plugin name="bot_controller" filename="libgazebo_ros_diff_drive.so">
        <commandTopic>cmd_vel</commandTopic>
        <odometryTopic>odom</odometryTopic>
        <odometryFrame>odom</odometryFrame>
        <odometrySource>world</odometrySource>
        <publishOdomTF>true</publishOdomTF>
        <robotBaseFrame>base_footprint</robotBaseFrame>
        <publishWheelTF>false</publishWheelTF>
        <publishTf>true</publishTf>
        <publishWheelJointState>true</publishWheelJointState>
        <legacyMode>false</legacyMode>
        <updateRate>30</updateRate>
        <leftJoint>left_joint</leftJoint>
        <rightJoint>right_joint</rightJoint>
        <wheelSeparation>${wheel_separation}</wheelSeparation>
        <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
        <wheelAcceleration>1</wheelAcceleration>
        <wheelTorque>10</wheelTorque>
        <rosDebugLevel>na</rosDebugLevel>
        </plugin>
    </gazebo>   

    <!--gazebo reference="base_scan">
        <sensor type="ray" name="lds_lfcd_sensor">
        <pose>0 0 0 0 0 0</pose>
        <visualize>true</visualize>
        <update_rate>5</update_rate>
        <ray>
            <scan>
            <horizontal>
                <samples>360</samples>
                <resolution>1</resolution>
                <min_angle>0.0</min_angle>
                <max_angle>6.28319</max_angle>
            </horizontal>
            </scan>
            <range>
            <min>0.120</min>
            <max>3.5</max>
            <resolution>0.015</resolution>
            </range>
            <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
            </noise>
        </ray>
        <plugin name="gazebo_ros_lds_lfcd_controller" filename="libgazebo_ros_laser.so">
            <topicName>scan</topicName>
            <frameName>base_scan</frameName>
        </plugin>
        </sensor>
    </gazebo-->

    <transmission name="left_wheel_trans" type="SimpleTransmission">
        <type>transmission_interface/SimpleTransmission</type>
            <actuator name="left_wheel_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        <joint name="left_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
    </transmission>

    <transmission name="right_wheel_trans" type="SimpleTransmission">
        <type>transmission_interface/SimpleTransmission</type>
            <actuator name="right_wheel_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        <joint name="right_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
    </transmission>
    
</robot>