<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="oryksbot">

  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>      
      <mass value="${m}"/>
      <inertia 
        ixx="${(m/12) * (h*h + d*d)}" 
        ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" 
        iyz="0.0" 
        izz="${(m/12) * (w*w + h*h)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />      
      <mass value="${m}"/>
      <inertia 
        ixx="${(m/12) * (3*r*r + h*h)}" 
        ixy = "0" 
        ixz = "0" 
        iyy="${(m/12) * (3*r*r + h*h)}"
        iyz = "0" 
        izz="${(m/2) * (r*r)}"/> 
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia 
        ixx="${(2/5) * m * (r*r)}" 
        ixy="0.0" 
        ixz="0.0" 
        iyy="${(2/5) * m * (r*r)}" 
        iyz="0.0" 
        izz="${(2/5) * m * (r*r)}"/>
    </inertial>
  </xacro:macro>

  <!-- Wheels -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect ">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${y_reflect*(pi/2)} 0 0"/> 
        <geometry>
          <mesh filename="package://oryksbot_description/meshes/${prefix}_wheel.STL" />
        </geometry>
        <material name="black" />
      </visual>

      <collision> 
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/> 
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_tread}"/>
        </geometry>
      </collision>

      <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_tread}"/>
    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*wheel_joint_offset_x} ${y_reflect*(base_width/2+wheel_joint_offset_y)} ${-base_height/2}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>
    
</robot>